#!/bin/bash
#
# benchmarking of 1..n summation: Gauss vs for loop summ

n=${1:-100}

# function for Gauss pair method
gauss() {
  echo Gauss: $((n*(n+1)/2))
} 

# function for the for loop
summation() {
  sum=0
  for ((i=1; i<=n; i++)); do
    ((sum+=$i))
  done
  echo Summation: $sum
}

echo Summ from 1 to $n:
# time <command> output execution time
time gauss
time summation
