#!/bin/bash

# Demo for running several tasks in parallel by sending
# them into the background

# catching signals to make sure the clean exit
trap 'killall $(jobs -p) 2>/dev/null' EXIT

# dummy sleep commands groupped with echo and sent to the background
for i in 1 3 5; do
  { sleep $i; echo sleep for $i s is over; } &  # remove ampesand for the serial execution
done

# 'wait' makes sure jobs are done before script is finished
# try to comment it to see the difference
wait
echo THE END
