#!/bin/bash

# expanding a string like 'xx[1,5,8-10],yy12,zz[3-5]' into
# 'xx1 xx5 xx8 xx9 xx10 yy12 zz3 zz4 zz5'

# Copyright (C) 2024 ivan.tervanto /at/ aalto.fi
# Released under the GNU General Public License


# expecting a string as an input parameter
(($#!=1)) && { echo "Usage: ${0##./} xx[1,3-6,8],yy4"; exit 1; }
string=$1

# let us collect the expanded list here
hostlist=()

# picking up [] entries first
regex="(([a-z]+)\[([0-9,-]+)\])"
# bash matches only the first entry, so we iterate to get them all
while [[ $string =~ $regex ]]; do
  # iteration over the list of numbers
  prefix="${BASH_REMATCH[2]}"
  nums="${BASH_REMATCH[3]}"
  for i in $(echo ${nums//,/ }); do
    if [[ $i =~ '-' ]]; then
      for j in $(eval echo {${i/-/..}}); do
        hostlist+=("${prefix}$j")
      done
    else
      hostlist+=("${prefix}$i")
    fi
  done
  string=${string/"${prefix}[${nums}]"/}
done

# picking the rest like xxxNN,yyyNN,...
regex="([a-z]+[0-9]+)"
while [[ $string =~ $regex ]]; do
  hostlist+=(${BASH_REMATCH[1]})
  string=${string/"${BASH_REMATCH[0]}"/}
done

# print out the list
printf "%s " "${hostlist[@]}"
echo
